### ISSUE TITLE
Error in 'sync install-tools'

### ISSUE THREAD

**Issue by gprossliner** [world-direct/k8s-setup#46]
```
TASK [sync install-tools] **********************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {
    "changed": false
}

MSG:

AnsibleUndefinedVariable: 'dict object' has no attribute 'version'
```

This seems to be related to the changes introduced by #44
